// Generated by scripts/generate-runtime-client-catalog.mjs.
// Source of truth: runtimes/*/runtime.toml and declared icon assets. Do not edit by hand.

import Foundation

public enum UnpeelRuntimeCapability: String, Equatable, Hashable, Sendable {
    case lifecycleHooks = "lifecycle_hooks"
    case resume = "resume"
    case restartAgent = "restart_agent"
    case mcpSessions = "mcp_sessions"
    case mcpBrowser = "mcp_browser"
    case mcpComputer = "mcp_computer"
    case transcript = "transcript"
    case notifyWhenDone = "notify_when_done"
    case semanticTerminalTitle = "semantic_terminal_title"
}

public enum UnpeelRuntimePlatform: String, Equatable, Hashable, Sendable {
    case macos = "macos"
    case linux = "linux"
}

/// Presentation family for sidebar logos and generic fallbacks. Adding a
/// runtime never requires a Swift case; set `display.kind` on the package
/// (a markdown-editor CLI uses `editor`). New families are added here
/// and generated — clients must not branch on command names.
public enum UnpeelRuntimeKind: String, Equatable, Hashable, Sendable {
    case agent = "agent"
    case app = "app"
    case editor = "editor"
    case terminal = "terminal"
}

public struct UnpeelRuntimeSuggestedPreset: Equatable, Sendable {
    public let id: String
    public let label: String
    public let command: String
    public let quickLaunch: Bool
}

public struct UnpeelRuntimeUsageStore: Equatable, Sendable {
    public let root: String
    public let extensions: Set<String>
    public let fileName: String?
    public let fileNameSuffix: String?
    public let parentDirName: String?
}

public struct UnpeelRuntimeMetadata: Equatable, Sendable {
    public let stableID: String
    public let slug: String
    public let legacySlug: String
    public let legacyOrder: Int?
    public let label: String
    public let platforms: Set<UnpeelRuntimePlatform>
    public let supportsQuickLaunch: Bool
    public let kind: UnpeelRuntimeKind
    public let tintColorHex: Int?
    public let spinnerTintColorHex: Int?
    public let iconKey: String
    public let iconSVG: String?
    public let iconIsTemplate: Bool
    public let iconSource: String?
    public let iconLicense: String?
    /// Horizontal Ghostty window padding in points. Zero is edge-to-edge.
    public let windowPaddingX: Int
    public let installURL: String?
    public let installCommand: String?
    public let commandAliases: [String]
    public let processAliases: [String]
    public let searchPathSuffixes: [String]
    public let lifecycleSource: String
    public let lifecycleAuthority: String
    public let lifecycleFallback: String
    public let completionReliable: Bool
    public let attentionReliable: Bool
    public let anchorStartEventToOutput: Bool
    public let attentionClearsOnOutput: Bool
    public let distrustStopsWhileOutputGrows: Bool
    public let capabilities: Set<UnpeelRuntimeCapability>
    public let usageStores: [UnpeelRuntimeUsageStore]
    public let suggestedPresets: [UnpeelRuntimeSuggestedPreset]

    public func supports(_ platform: UnpeelRuntimePlatform) -> Bool {
        platforms.contains(platform)
    }
    public var defaultPreset: UnpeelRuntimeSuggestedPreset? { suggestedPresets.first }
    public var presentationCommand: String? { commandAliases.first }
}

/// Presentation, setup, and declared-capability metadata shared by clients.
/// Runtime recipes and effective per-Session actions remain Host-owned.
public enum UnpeelRuntimeCatalog {
    public static let runtimes: [UnpeelRuntimeMetadata] = [
        // runtimes/claude-code/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.anthropic.claude-code",
            slug: "claude-code",
            legacySlug: "claude",
            legacyOrder: 0,
            label: "Claude",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0xD97757,
            spinnerTintColorHex: 0xD97757,
            iconKey: "claude",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"#FFFFFF\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4.709 15.955l4.72-2.647.08-.23-.08-.128H9.2l-.79-.048-2.698-.073-2.339-.097-2.266-.122-.571-.121L0 11.784l.055-.352.48-.321.686.06 1.52.103 2.278.158 1.652.097 2.449.255h.389l.055-.157-.134-.098-.103-.097-2.358-1.596-2.552-1.688-1.336-.972-.724-.491-.364-.462-.158-1.008.656-.722.881.06.225.061.893.686 1.908 1.476 2.491 1.833.365.304.145-.103.019-.073-.164-.274-1.355-2.446-1.446-2.49-.644-1.032-.17-.619a2.97 2.97 0 01-.104-.729L6.283.134 6.696 0l.996.134.42.364.62 1.414 1.002 2.229 1.555 3.03.456.898.243.832.091.255h.158V9.01l.128-1.706.237-2.095.23-2.695.08-.76.376-.91.747-.492.584.28.48.685-.067.444-.286 1.851-.559 2.903-.364 1.942h.212l.243-.242.985-1.306 1.652-2.064.73-.82.85-.904.547-.431h1.033l.76 1.129-.34 1.166-1.064 1.347-.881 1.142-1.264 1.7-.79 1.36.073.11.188-.02 2.856-.606 1.543-.28 1.841-.315.833.388.091.395-.328.807-1.969.486-2.309.462-3.439.813-.042.03.049.061 1.549.146.662.036h1.622l3.02.225.79.522.474.638-.079.485-1.215.62-1.64-.389-3.829-.91-1.312-.329h-.182v.11l1.093 1.068 2.006 1.81 2.509 2.33.127.578-.322.455-.34-.049-2.205-1.657-.851-.747-1.926-1.62h-.128v.17l.444.649 2.345 3.521.122 1.08-.17.353-.608.213-.668-.122-1.374-1.925-1.415-2.167-1.143-1.943-.14.08-.674 7.254-.316.37-.729.28-.607-.461-.322-.747.322-1.476.389-1.924.315-1.53.286-1.9.17-.632-.012-.042-.14.018-1.434 1.967-2.18 2.945-1.726 1.845-.414.164-.717-.37.067-.662.401-.589 2.388-3.036 1.44-1.882.93-1.086-.006-.158h-.055L4.132 18.56l-1.13.146-.487-.456.061-.746.231-.243 1.908-1.312-.006.006z\" fill-rule=\"nonzero\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://claude.com/claude-code",
            installCommand: "npm install -g @anthropic-ai/claude-code",
            commandAliases: ["claude"],
            processAliases: ["claude", "claude-code"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .mcpSessions, .mcpBrowser, .mcpComputer, .transcript, .notifyWhenDone, .semanticTerminalTitle],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".claude/projects",
                    extensions: Set(["jsonl"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "claude",
                    label: "claude",
                    command: "claude",
                    quickLaunch: true
                ),
            ]
        ),
        // runtimes/codex/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.openai.codex",
            slug: "codex",
            legacySlug: "codex",
            legacyOrder: 1,
            label: "Codex",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0xC292FE,
            spinnerTintColorHex: 0xC292FE,
            iconKey: "codex",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"#FFFFFF\" fill-rule=\"evenodd\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M9.205 8.658v-2.26c0-.19.072-.333.238-.428l4.543-2.616c.619-.357 1.356-.523 2.117-.523 2.854 0 4.662 2.212 4.662 4.566 0 .167 0 .357-.024.547l-4.71-2.759a.797.797 0 00-.856 0l-5.97 3.473zm10.609 8.8V12.06c0-.333-.143-.57-.429-.737l-5.97-3.473 1.95-1.118a.433.433 0 01.476 0l4.543 2.617c1.309.76 2.189 2.378 2.189 3.948 0 1.808-1.07 3.473-2.76 4.163zM7.802 12.703l-1.95-1.142c-.167-.095-.239-.238-.239-.428V5.899c0-2.545 1.95-4.472 4.591-4.472 1 0 1.927.333 2.712.928L8.23 5.067c-.285.166-.428.404-.428.737v6.898zM12 15.128l-2.795-1.57v-3.33L12 8.658l2.795 1.57v3.33L12 15.128zm1.796 7.23c-1 0-1.927-.332-2.712-.927l4.686-2.712c.285-.166.428-.404.428-.737v-6.898l1.974 1.142c.167.095.238.238.238.428v5.233c0 2.545-1.974 4.472-4.614 4.472zm-5.637-5.303l-4.544-2.617c-1.308-.761-2.188-2.378-2.188-3.948A4.482 4.482 0 014.21 6.327v5.423c0 .333.143.571.428.738l5.947 3.449-1.95 1.118a.432.432 0 01-.476 0zm-.262 3.9c-2.688 0-4.662-2.021-4.662-4.519 0-.19.024-.38.047-.57l4.686 2.71c.286.167.571.167.856 0l5.97-3.448v2.26c0 .19-.07.333-.237.428l-4.543 2.616c-.619.357-1.356.523-2.117.523zm5.899 2.83a5.947 5.947 0 005.827-4.756C22.287 18.339 24 15.84 24 13.296c0-1.665-.713-3.282-1.998-4.448.119-.5.19-.999.19-1.498 0-3.401-2.759-5.947-5.946-5.947-.642 0-1.26.095-1.88.31A5.962 5.962 0 0010.205 0a5.947 5.947 0 00-5.827 4.757C1.713 5.447 0 7.945 0 10.49c0 1.666.713 3.283 1.998 4.448-.119.5-.19 1-.19 1.499 0 3.401 2.759 5.946 5.946 5.946.642 0 1.26-.095 1.88-.309a5.96 5.96 0 004.162 1.713z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://openai.com/codex",
            installCommand: "npm install -g @openai/codex",
            commandAliases: ["codex"],
            processAliases: ["codex"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: true,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .mcpSessions, .mcpBrowser, .mcpComputer, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".codex/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "codex",
                    label: "codex --dangerously-bypass-approvals-and-sandbox",
                    command: "codex --dangerously-bypass-approvals-and-sandbox",
                    quickLaunch: true
                ),
            ]
        ),
        // runtimes/cline/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "bot.cline.cli",
            slug: "cline",
            legacySlug: "cline",
            legacyOrder: 2,
            label: "Cline",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0xF26C5A,
            spinnerTintColorHex: 0x98C4FA,
            iconKey: "cline",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 466.73 487.04\" fill=\"#FFFFFF\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M463.6,275.08l-29.26-58.75v-33.83c0-56.08-45.01-101.5-100.53-101.5h-50.01c3.62-7.43,5.61-15.79,5.61-24.61,0-31.17-25.08-56.39-56.07-56.39s-56.07,25.22-56.07,56.39c0,8.82,1.99,17.17,5.61,24.61h-50.01c-55.51,0-100.52,45.42-100.52,101.5v33.83l-29.87,58.59c-3.01,5.9-3.01,12.92,0,18.81l29.87,57.93v33.83c0,56.08,45.01,101.5,100.52,101.5h200.95c55.51,0,100.53-45.42,100.53-101.5v-33.83l29.21-58.13c2.9-5.79,2.9-12.61.05-18.46ZM202.75,322.96c0,25.48-20.54,46.14-45.88,46.14s-45.88-20.66-45.88-46.14v-82.02c0-25.48,20.54-46.14,45.88-46.14s45.88,20.66,45.88,46.14v82.02ZM350.58,322.96c0,25.48-20.54,46.14-45.88,46.14s-45.88-20.66-45.88-46.14v-82.02c0-25.48,20.54-46.14,45.88-46.14s45.88,20.66,45.88,46.14v82.02Z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://cline.bot",
            installCommand: "npm install -g cline",
            commandAliases: ["cline"],
            processAliases: ["cline"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "partial",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: false,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .mcpSessions, .mcpBrowser, .mcpComputer, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".cline/data/sessions",
                    extensions: Set(["json"]),
                    fileName: nil,
                    fileNameSuffix: ".messages.json",
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "cline",
                    label: "cline",
                    command: "cline",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/amp/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.sourcegraph.amp",
            slug: "amp",
            legacySlug: "amp",
            legacyOrder: 3,
            label: "Amp",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0xF97316,
            spinnerTintColorHex: 0xF97316,
            iconKey: "amp",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"#FFFFFF\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12 2 2 22h4.4l1.82-4.2h7.56L17.6 22H22L12 2Zm-2.05 11.9L12 9.08l2.05 4.82H9.95Z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://ampcode.com",
            installCommand: "npm install -g @sourcegraph/amp",
            commandAliases: ["amp"],
            processAliases: ["amp", "amp-local"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "partial",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: false,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .notifyWhenDone],
            usageStores: [
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "amp",
                    label: "amp",
                    command: "amp",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/gemini/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.google.gemini-cli",
            slug: "gemini",
            legacySlug: "gemini",
            legacyOrder: 4,
            label: "Gemini",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0x6EA8FF,
            spinnerTintColorHex: 0x6EA8FF,
            iconKey: "gemini",
            iconSVG: "<svg width=\"16\" height=\"16\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 16\"><path d=\"M16 8.016A8.522 8.522 0 008.016 16h-.032A8.521 8.521 0 000 8.016v-.032A8.521 8.521 0 007.984 0h.032A8.522 8.522 0 0016 7.984v.032z\" fill=\"#FFFFFF\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://github.com/google-gemini/gemini-cli",
            installCommand: "npm install -g @google/gemini-cli",
            commandAliases: ["gemini"],
            processAliases: ["gemini"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".gemini/tmp",
                    extensions: Set(["json", "jsonl"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: "chats"
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "gemini",
                    label: "gemini --yolo",
                    command: "gemini --yolo",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/pi/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "dev.mariozechner.pi",
            slug: "pi",
            legacySlug: "pi",
            legacyOrder: 5,
            label: "Pi",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0x7C95FF,
            spinnerTintColorHex: 0x7C95FF,
            iconKey: "pi",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 800 800\" fill=\"#FFFFFF\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M165.29 165.29H517.36V400H400V517.36H282.65V634.72H165.29ZM282.65 282.65V400H400V282.65Z\"/><path d=\"M517.36 400H634.72V634.72H517.36Z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://github.com/badlogic/pi-mono",
            installCommand: "npm install -g @mariozechner/pi-coding-agent",
            commandAliases: ["pi"],
            processAliases: ["pi"],
            searchPathSuffixes: [],
            lifecycleSource: "output",
            lifecycleAuthority: "none",
            lifecycleFallback: "none",
            completionReliable: false,
            attentionReliable: false,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.resume, .restartAgent],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".pi/agent/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "pi",
                    label: "pi",
                    command: "pi",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/opencode/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "ai.opencode.cli",
            slug: "opencode",
            legacySlug: "opencode",
            legacyOrder: 6,
            label: "OpenCode",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0x8F8787,
            spinnerTintColorHex: 0x8F8787,
            iconKey: "opencode",
            iconSVG: "<svg width=\"13\" height=\"16\" viewBox=\"0 0 240 300\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M0 0H240V300H0V0ZM60 60H180V240H60V60Z\" fill=\"#F1ECEC\"/><path d=\"M60 120H180V240H60V120Z\" fill=\"#4B4646\"/></svg>",
            iconIsTemplate: false,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 0,
            installURL: "https://opencode.ai",
            installCommand: "npm install -g opencode-ai",
            commandAliases: ["opencode"],
            processAliases: ["opencode", "opencode2"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".local/share/opencode/storage/session",
                    extensions: Set(["json"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "opencode",
                    label: "opencode",
                    command: "opencode",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/github-copilot/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.github.copilot-cli",
            slug: "github-copilot",
            legacySlug: "copilot",
            legacyOrder: 7,
            label: "Copilot",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: nil,
            spinnerTintColorHex: nil,
            iconKey: "agent",
            iconSVG: nil,
            iconIsTemplate: true,
            iconSource: nil,
            iconLicense: nil,
            windowPaddingX: 8,
            installURL: "https://github.com/github/copilot-cli",
            installCommand: "npm install -g @github/copilot",
            commandAliases: ["copilot"],
            processAliases: ["copilot", "github-copilot", "ghcs"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .notifyWhenDone],
            usageStores: [
            ],
            suggestedPresets: [
            ]
        ),
        // runtimes/cursor-agent/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.cursor.agent",
            slug: "cursor-agent",
            legacySlug: "cursor-agent",
            legacyOrder: 8,
            label: "Cursor Agent",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0x22C55D,
            spinnerTintColorHex: 0x22C55D,
            iconKey: "cursor",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"#FFFFFF\" fill-rule=\"evenodd\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M22.106 5.68L12.5.135a.998.998 0 00-.998 0L1.893 5.68a.84.84 0 00-.419.726v11.186c0 .3.16.577.42.727l9.607 5.547a.999.999 0 00.998 0l9.608-5.547a.84.84 0 00.42-.727V6.407a.84.84 0 00-.42-.726zm-.603 1.176L12.228 22.92c-.063.108-.228.064-.228-.061V12.34a.59.59 0 00-.295-.51l-9.11-5.26c-.107-.062-.063-.228.062-.228h18.55c.264 0 .428.286.296.514z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://cursor.com/cli",
            installCommand: "curl https://cursor.com/install -fsS | bash",
            commandAliases: ["cursor-agent"],
            processAliases: ["cursor-agent"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .mcpSessions, .mcpBrowser, .mcpComputer, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".cursor/projects",
                    extensions: Set(["jsonl"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "cursor-agent",
                    label: "cursor-agent --force",
                    command: "cursor-agent --force",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/grok/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "ai.x.grok-cli",
            slug: "grok",
            legacySlug: "grok",
            legacyOrder: 9,
            label: "Grok",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0x8F8787,
            spinnerTintColorHex: 0x8F8787,
            iconKey: "grok",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"#FFFFFF\" fill-rule=\"evenodd\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M9.27 15.29l7.978-5.897c.391-.29.95-.177 1.137.272.98 2.369.542 5.215-1.41 7.169-1.951 1.954-4.667 2.382-7.149 1.406l-2.711 1.257c3.889 2.661 8.611 2.003 11.562-.953 2.341-2.344 3.066-5.539 2.388-8.42l.006.007c-.983-4.232.242-5.924 2.75-9.383.06-.082.12-.164.179-.248l-3.301 3.305v-.01L9.267 15.292M7.623 16.723c-2.792-2.67-2.31-6.801.071-9.184 1.761-1.763 4.647-2.483 7.166-1.425l2.705-1.25a7.808 7.808 0 00-1.829-1A8.975 8.975 0 005.984 5.83c-2.533 2.536-3.33 6.436-1.962 9.764 1.022 2.487-.653 4.246-2.34 6.022-.599.63-1.199 1.259-1.682 1.925l7.62-6.815\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 0,
            installURL: "https://x.ai",
            installCommand: "curl -fsSL https://x.ai/cli/install.sh | bash",
            commandAliases: ["grok"],
            processAliases: ["grok", "grok-build"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: false,
            attentionClearsOnOutput: false,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".grok/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "grok",
                    label: "grok --always-approve",
                    command: "grok --always-approve",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/kimi/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.moonshot.kimi-code",
            slug: "kimi",
            legacySlug: "kimi",
            legacyOrder: 10,
            label: "Kimi",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0x8B7CFF,
            spinnerTintColorHex: 0xB88A2A,
            iconKey: "kimi",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"#FFFFFF\" fill-rule=\"evenodd\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M21.846 0a1.923 1.923 0 110 3.846H20.15a.226.226 0 01-.227-.226V1.923C19.923.861 20.784 0 21.846 0z\"/><path d=\"M11.065 11.199l7.257-7.2c.137-.136.06-.41-.116-.41H14.3a.164.164 0 00-.117.051l-7.82 7.756c-.122.12-.302.013-.302-.179V3.82c0-.127-.083-.23-.185-.23H3.186c-.103 0-.186.103-.186.23V19.77c0 .128.083.23.186.23h2.69c.103 0 .186-.102.186-.23v-3.25c0-.069.025-.135.069-.178l2.424-2.406a.158.158 0 01.205-.023l6.484 4.772a7.677 7.677 0 003.453 1.283c.108.012.2-.095.2-.23v-3.06c0-.117-.07-.212-.164-.227a5.028 5.028 0 01-2.027-.807l-5.613-4.064c-.117-.078-.132-.279-.028-.381z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://kimi.com",
            installCommand: nil,
            commandAliases: ["kimi"],
            processAliases: ["kimi", "kimi-code"],
            searchPathSuffixes: [".kimi-code/bin"],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .mcpSessions, .mcpBrowser, .mcpComputer, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".kimi-code/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: "wire.jsonl",
                    fileNameSuffix: nil,
                    parentDirName: "main"
                ),
                UnpeelRuntimeUsageStore(
                    root: ".kimi/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: "context.jsonl",
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "kimi",
                    label: "kimi --yolo",
                    command: "kimi --yolo",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/kiro/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "dev.kiro.cli",
            slug: "kiro",
            legacySlug: "kiro-cli",
            legacyOrder: 11,
            label: "Kiro",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0xA78BFA,
            spinnerTintColorHex: 0xA78BFA,
            iconKey: "kiro",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"#FFFFFF\" fill-rule=\"evenodd\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M4.594 6.677C6.67-2.226 18.746-2.211 21.16 6.632c.353 1.297 1.725 7.582-1.673 13.747-1.545 2.797-5.841 5.49-6.99 1.883C8.6 25.477 3.315 24.1 5.789 18.609l-.318.143c-3.57 1.305-3.863-1.208-3.173-2.513.45-.84.727-1.335.937-1.897.353-.975.458-1.568.593-2.498.27-1.837.277-3.607.765-5.167zm8.37.01a.92.92 0 00-.81.428c-.217.323-.33.825-.33 1.462 0 .705.15 1.89 1.14 1.89h.008c.757 0 1.214-.705 1.214-1.89 0-.622-.127-1.125-.367-1.455a1.014 1.014 0 00-.855-.435zm4.08 0a.92.92 0 00-.81.428c-.217.323-.33.825-.33 1.462 0 .705.15 1.89 1.14 1.89h.008c.757 0 1.215-.705 1.215-1.89 0-.622-.128-1.125-.368-1.455a1.014 1.014 0 00-.855-.435z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://kiro.dev",
            installCommand: nil,
            commandAliases: ["kiro-cli"],
            processAliases: ["kiro", "kiro-cli"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .mcpSessions, .mcpBrowser, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".kiro/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: nil,
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "kiro-cli",
                    label: "kiro-cli --v3",
                    command: "kiro-cli --v3",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/muse-code/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "ai.meta.muse-code",
            slug: "muse-code",
            legacySlug: "muse",
            legacyOrder: 12,
            label: "Muse Code",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0x0082FB,
            spinnerTintColorHex: 0x0082FB,
            iconKey: "muse",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"0 0 800 800\" fill=\"#FFFFFF\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M197 313C131 313 63 277 63 225C63 177 120 145 182 145C248 145 316 181 316 234C316 284 256 313 197 313Z\"/><path d=\"M95 567C55 567 29 540 29 499C29 429 105 349 175 349C216 349 240 376 240 416C240 488 164 567 95 567Z\"/><path d=\"M365 660C365 712 338 769 290 769C234 769 194 691 194 626C194 573 221 518 269 518C327 518 365 599 365 660Z\"/><path d=\"M553 742C482 742 398 680 398 614C398 571 434 550 476 550C548 550 633 613 633 677C633 719 596 742 553 742Z\"/><path d=\"M785 439C785 505 695 555 627 555C575 555 542 525 542 486C542 422 630 371 700 371C751 371 785 398 785 439Z\"/><path d=\"M596 356C550 356 525 310 525 261C525 195 570 109 632 109C678 109 702 157 702 205C702 269 659 356 596 356Z\"/><path d=\"M502 172C502 213 480 243 439 243C370 243 303 157 303 87C303 47 325 15 367 15C436 15 502 101 502 172Z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "internal:legacy-unpeel-tool-icons",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://dev.meta.ai",
            installCommand: "curl -fsSL https://dev.meta.ai/install.sh | bash",
            commandAliases: ["muse"],
            processAliases: ["muse"],
            searchPathSuffixes: [],
            lifecycleSource: "hooks",
            lifecycleAuthority: "complete",
            lifecycleFallback: "none",
            completionReliable: true,
            attentionReliable: true,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.lifecycleHooks, .resume, .restartAgent, .transcript, .notifyWhenDone],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".local/share/muse/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: "session.jsonl",
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "muse",
                    label: "muse --yolo",
                    command: "muse --yolo",
                    quickLaunch: false
                ),
            ]
        ),
        // runtimes/fx/runtime.toml
        UnpeelRuntimeMetadata(
            stableID: "com.vercel.fx",
            slug: "fx",
            legacySlug: "fx",
            legacyOrder: 13,
            label: "fx",
            platforms: Set([.macos, .linux]),
            supportsQuickLaunch: true,
            kind: .agent,
            tintColorHex: 0xEDEDED,
            spinnerTintColorHex: 0xEDEDED,
            iconKey: "fx",
            iconSVG: "<svg width=\"16\" height=\"16\" viewBox=\"166.241 0 155.861 156\" fill=\"#FFFFFF\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M237.89 0C243.18 0 249.38 1.42 253.03 3.07L255.09 4.01L250.08 18.63L247.68 17.75C244.9 16.72 241.94 15.8 238.49 15.8C234.98 15.8 232.79 16.56 231.08 18.32C229.23 20.23 227.63 23.64 226.23 29.76L226.23 29.76L226.23 29.76L225.14 34.85H241.67L260.43 34.95L260.69 34.95L260.84 35.17L278.85 61.63L296.74 34.95H320.87L291.68 76.74L322.1 119.75H299.33L299.18 119.55L241.14 40.48L239.35 49.4H222.07L205.69 127.21C203.93 135.71 201.19 142.84 196.78 147.87C192.27 153.01 186.2 155.75 178.34 155.75C174.18 155.75 170.75 155.11 167.91 154.11L166.24 153.52V137.18L166.9 137.4L169.53 138.28C172.18 139.16 174.41 139.8 177.14 139.8C178.53 139.8 179.7 139.53 180.73 138.98C181.76 138.43 182.68 137.6 183.52 136.44C185.3 133.99 186.72 130.13 187.9 124.67L203.76 49.4H189.87L191.76 39.44L192.04 39.35L206.82 34.47L208.15 28.64C210.52 18.21 213.77 10.94 218.71 6.32C223.74 1.61 230.13 0 237.89 0ZM273.99 99.08L260.07 120.25H234.54L261 82.02L273.99 99.08Z\"/></svg>",
            iconIsTemplate: true,
            iconSource: "https://fx.sh",
            iconLicense: "vendor-brand-asset",
            windowPaddingX: 8,
            installURL: "https://fx.sh",
            installCommand: "curl -fsSL https://fx.sh/setup.sh | bash",
            commandAliases: ["fx"],
            processAliases: ["fx"],
            searchPathSuffixes: [],
            lifecycleSource: "output",
            lifecycleAuthority: "none",
            lifecycleFallback: "none",
            completionReliable: false,
            attentionReliable: false,
            anchorStartEventToOutput: true,
            attentionClearsOnOutput: true,
            distrustStopsWhileOutputGrows: false,
            capabilities: [.resume, .restartAgent, .mcpSessions, .mcpBrowser],
            usageStores: [
                UnpeelRuntimeUsageStore(
                    root: ".fx/sessions",
                    extensions: Set(["jsonl"]),
                    fileName: "events.jsonl",
                    fileNameSuffix: nil,
                    parentDirName: nil
                ),
            ],
            suggestedPresets: [
                UnpeelRuntimeSuggestedPreset(
                    id: "fx",
                    label: "fx",
                    command: "fx",
                    quickLaunch: false
                ),
            ]
        ),
    ]

    private static let identityIndex: [String: Int] = {
        var result: [String: Int] = [:]
        for (index, runtime) in runtimes.enumerated() {
            let identities = [runtime.stableID, runtime.slug, runtime.legacySlug]
                + runtime.processAliases
            for identity in identities { result[identity.lowercased()] = index }
        }
        return result
    }()

    private static let commandIndex: [String: Int] = {
        var result: [String: Int] = [:]
        for (index, runtime) in runtimes.enumerated() {
            for alias in runtime.commandAliases { result[alias.lowercased()] = index }
        }
        return result
    }()

    public static func runtime(id: String?) -> UnpeelRuntimeMetadata? {
        guard let key = id?.trimmingCharacters(in: .whitespacesAndNewlines).lowercased(),
              let index = identityIndex[key] else { return nil }
        return runtimes[index]
    }

    public static func runtime(command: String) -> UnpeelRuntimeMetadata? {
        let token = command
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .split(whereSeparator: { $0.isWhitespace })
            .first
            .map(String.init)
        guard let token else { return nil }
        let head = (token as NSString).lastPathComponent.lowercased()
        guard let index = commandIndex[head] else { return nil }
        return runtimes[index]
    }

    public static func runtimes(for platform: UnpeelRuntimePlatform) -> [UnpeelRuntimeMetadata] {
        runtimes(for: platform, from: runtimes)
    }

    static func runtimes(
        for platform: UnpeelRuntimePlatform,
        from candidates: [UnpeelRuntimeMetadata]
    ) -> [UnpeelRuntimeMetadata] {
        candidates.filter { $0.supports(platform) }
    }

    public static func runtime(id: String?, for platform: UnpeelRuntimePlatform) -> UnpeelRuntimeMetadata? {
        guard let runtime = runtime(id: id), runtime.supports(platform) else { return nil }
        return runtime
    }

    public static func runtime(command: String, for platform: UnpeelRuntimePlatform) -> UnpeelRuntimeMetadata? {
        guard let runtime = runtime(command: command), runtime.supports(platform) else { return nil }
        return runtime
    }

    public static func presentationCommand(forRuntimeID id: String?) -> String? {
        runtime(id: id)?.presentationCommand
    }
}
